### PR TITLE
Fix type declaration

### LINKED ISSUE #1: Inconsistency in type declaration
https://github.com/FredT2020/gstadv/blob/38323e427e70c84b63e2e6efb8a47ff6e5251315/plugins/gstadvaudiosrc.h#L38

is inconsistent with the use of `GstPushSrcClass` just below.

### PR DESCRIPTION
**Pull request by philn**
Fixes #1

### CODE REVIEW

**Comment by FredT2020** [comment]
@philn Thanks. That make sense. However, this should be ultimately a pushSrc since it won't be seekable. 
If I want to use pushsrc, I should get it from gst base but when I try I get the same problem. Do I need to make a change somewhere else?

**Comment by philn** [comment]
Yeah, I figured. See the Pull request, #2 :)

**Comment by philn** [comment]
AudioSrc already inherits from PushSrc:
```
Factory Details:
  Rank                     none (0)
  Long-name                FIXME Long name
  Klass                    Generic
  Description              FIXME Description
  Author                   FIXME <fixme@example.com>

Plugin Details:
  Name                     adv
  Description              FIXME Template plugin
  Filename                 /tmp/gstadv/build/plugins/libgstadv.dylib
  Version                  0.0.FIXME
  License                  LGPL
  Source module            gst-project-plugin
  Binary package           GStreamer
  Origin URL               http://gstreamer.net/

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseSrc
                         +----GstPushSrc
                               +----GstAudioBaseSrc
                                     +----GstAudioSrc
                                           +----GstAdvAudioSrc

```

**Comment by philn** [comment]
In your plugin code you can easily cast the audiosrc to pushsrc with the `GST_PUSH_SRC()` macro.

**Comment by FredT2020** [comment]
@philn  Thanks what is the benefit of audiosrc instead of using pushsrc directly as in  Decklink and Aja plugin? and where the macro should be used? as you can guest I'm a newbie when it comes to write a plugin.

**Comment by philn** [comment]
If you write an audiosrc element I think it makes sense to use gstaudiosrc as a base-class, it's documented there: https://gstreamer.freedesktop.org/documentation/audio/gstaudiosrc.html?gi-language=c#GstAudioSrc

I don't know why the Decklink and Aja don't use this base class.

Regarding seek, I see that audiobasesrc already configures itself as a live source: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/master/gst-libs/gst/audio/gstaudiobasesrc.c#L235
So perhaps you'd just need to implement the audiosrc vfuncs without worrying about seek ability.

**Comment by philn** [comment]
Maybe the Decklink and Aja plugins don't need ring-buffer support? That's one of the main benefit of using Gstaudiobasesrc and gstaudiosrc.

**Comment by FredT2020** [comment]
@philn I will likely need a ring buffer because my audio data will come in a callback.
So with you suggested change, gst-inspect does not complain when put the full path of the .so file. However when I copy it in my gstreamer lib directory it does not recognize it. 
I tried deleting the cache but did not help.
Any idea?

**Comment by philn** [comment]
It should work. But you don't need to copy your plugin anywhere for development purpose. I'd recommend to use GST_PLUGIN_PATH env var: `GST_PLUGIN_PATH=$PWD/build/plugins/ gst-inspect-1.0 advaudiosrc` where build is the meson build directory.

**Comment by FredT2020** [comment]
No luck.

**Comment by philn** [comment]
In which directory exactly are you copying the plugin?

**Comment by FredT2020** [comment]
I tried usr/local/lib where other gst plugins are.
I also tried GST_PLUGIN_PATH

**Comment by philn** [comment]
Sounds like you have a messed-up gst installation? For development I'd recommend gst-build (uninstalled) and there, within the gst-env shell, compile your plugin and add your build dir in the GST_PLUGIN_PATH

**Comment by FredT2020** [comment]
ho wait... It works with GST_PLUGIN_PATH .. There was a typo

But does not explain why it does not work in usr/local/lib

**Comment by philn** [comment]
Anything manually installed in /usr/local sounds like trouble to me. Please rely on your distro packages and keep gst-build uninstalled, as advised above :)

**Comment by FredT2020** [comment]
Thanks for your help.

**Pull request closed without merging**
